updating rust version from 1.88 to 1.89 due to these errror observed
error: rustc 1.88.0 is not supported by the following packages:
  iroh@0.96.1 requires rustc 1.89
  iroh-base@0.96.1 requires rustc 1.89
  iroh-relay@0.96.1 requires rustc 1.89
  iroh-relay-holochain@0.96.1 requires rustc 1.89
  netwatch@0.14.0 requires rustc 1.89
  portmapper@0.14.0 requires rustc 1.89
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.88.0

failed to build app: failed to build app
       Error [tauri_cli_node] failed to build app: failed to build app
Error: Command "npm ["run","tauri","build","--","--verbose","--features","holochain_bundled"]" failed with exit code 1